/**
 * Generate CSS variables from theme.js
 * Converts the theme object into CSS custom properties for use in stylesheets
 */

const fs = require('fs');
const path = require('path');
const theme = require('../src/css/theme').default;

// Convert camelCase or UPPER_CASE to kebab-case
function toKebabCase(str: string): string {
  return str
    // Handle UPPER_CASE (e.g., PRIMARY_LIGHT -> primary-light)
    .replace(/_/g, '-')
    // Handle camelCase (e.g., borderRadius -> border-radius)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

// Recursively convert theme object to CSS variables
function generateCssVars(obj: any, prefix: string = ''): string[] {
  const vars: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const kebabKey = toKebabCase(key);
    const varName = prefix ? `${prefix}-${kebabKey}` : kebabKey;

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Recursively handle nested objects
      vars.push(...generateCssVars(value, varName));
    } else {
      // Create CSS variable declaration
      vars.push(`  --${varName}: ${value};`);
    }
  }

  return vars;
}

// Generate the CSS file
function main() {
  const cssVars = generateCssVars(theme);

  const cssContent = `/**
 * CSS Variables generated from theme.js
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'yarn generate:css-vars' to regenerate
 */

:root {
${cssVars.join('\n')}
}
`;

  const outputPath = path.join(__dirname, '../src/css/variables.css');
  fs.writeFileSync(outputPath, cssContent, 'utf8');

  console.log(`✅ Generated CSS variables at: ${outputPath}`);
  console.log(`   ${cssVars.length} variables created`);
}

main();
