parser: 'babel-eslint'

extends:
  - 'react-app'
  - 'plugin:prettier/recommended'

plugins:
  - 'babel'
  - 'prettier'

settings:
  react:
    version: 'detect'

env:
  browser: true
  node: true

rules:
  prettier/prettier:
    - 2
    - bracketSpacing: true
      singleQuote: true
      tabWidth: 2
      trailingComma: 'es5'

overrides:
  - files: '**/*.test.js'
    rules:
      no-class-assign: 0
      no-console: 0
      no-unused-vars: 0
      no-unused-expressions: 0

error:
  endOfLine: auto
