steps:
  - name: node:20
    entrypoint: yarn
  - name: node:20
    entrypoint: yarn
    args: ['build']
  - name: "gcr.io/cloud-builders/gcloud-slim"
    args: [
      "storage",
      "cp",
      "--recursive",
      "build",
      "gs://optimum-library-250223_cloudbuild/build",
    ]
