steps:
  - name: node:24
    entrypoint: bash
    args: ['-c', 'corepack enable && yarn install && yarn build']
  - name: "gcr.io/cloud-builders/gcloud-slim"
    args: [
      "storage",
      "cp",
      "--recursive",
      "build",
      "gs://optimum-library-250223_cloudbuild/build",
    ]
