/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account info that the frontend/browser/client can't modify through sync/patch
 */
export interface AccountReadOnly {
  /**
   * Random 64-bit unique identifier for this game
   */
  accountId?: string;
  /**
   * Account's associate email
   */
  email?: string;
  /**
   * Whether the email validation link has been clicked or not
   */
  emailConfirmed?: boolean;
  /**
   * Number of optimizer credits the account has remaining
   */
  balance?: number;
  [k: string]: unknown;
}
