/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Information about an individual plate appearance
 */
export interface PlateAppearance {
  /**
   * Random 64-bit unique identifier for this plate appearance
   */
  id: string;
  /**
   * The id of the player who is the batter during the plate appearance
   */
  playerId: string;
  /**
   * The outcome of the plate appearance for the batter (e.g. BB, E, 1B, etc.)
   */
  result: string | null;
  /**
   * Location of runners after the conclusion of the plate appearance
   */
  runners?: {
    "1B"?: string;
    "2B"?: string;
    "3B"?: string;
    scored?: string[];
    /**
     * @maxItems 3
     */
    out?: [] | [string] | [string, string] | [string, string, string];
  };
  /**
   * Where the ball was hit
   */
  location: {
    /**
     * X coordinate of where the ball was fielded (or where the ball ended at the end of the plate appearance if not fielded). Expressed as 32767ths of the field image from the left
     */
    x: number | null;
    /**
     * Y coordinate of where the ball was fielded (or where the ball ended at the end of the plate appearance if not fielded). Expressed as 32767ths of the field image from the top
     */
    y: number | null;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
