/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
import type {TeamId, GameId, PlayerId, PlateAppearanceId, OptimizationId} from "./branded-ids";

/**
 * Information a player
 */
export interface Player {
  /**
   * Random 64-bit unique identifier for this player
   */
  id: PlayerId;
  /**
   * Name of the player
   */
  name: string;
  /**
   * Gender of the player
   */
  gender: string;
  /**
   * Walkup song YouTube link
   */
  songLink: string | null;
  /**
   * Walkup song start time in seconds
   */
  songStart: number | null;
  [k: string]: unknown;
}
