/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TeamReadOnly {
  /**
   * Whether or not the stats for the team should be available at a public web address
   */
  publicIdEnabled?: boolean;
  /**
   * The unique identifier used to construct the public web address for this teams stats (if enabled)
   */
  publicId?: string;
  [k: string]: unknown;
}
