/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account info that can be sent to the frontend/browser/client
 */
export interface Account {
  /**
   * A list of optimizer ids that the account has selected
   */
  optimizers: unknown[];
  [k: string]: unknown;
}
