/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account info that should never be sent to the frontend/browser/client
 */
export interface AccountPrivate {
  /**
   * Account password hash
   */
  passwordHash: string;
  /**
   * Token used for email confirmation and/or password reset
   */
  passwordTokenHash: string;
  /**
   * When the passwordTokenHash expires and can no longer be sed to reset email or validate email address
   */
  passwordTokenExpiration: number;
  [k: string]: unknown;
}
