/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OptimizationReadOnly {
  /**
   * Indicates what state the optimization is currently in e.g. NOT_STARTED, IN_PROGRESS, COMPLETE etc.
   */
  status?: number;
  /**
   * Whether the user has requested that the optimization be paused or not
   */
  pause?: boolean;
  [k: string]: unknown;
}
